// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chineseZodiac.proto

package proto;

public final class ChineseZodiac {
  private ChineseZodiac() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023chineseZodiac.proto\032\ngate.proto2J\n\024Chi" +
      "neseZodiacService\0222\n\rgetZodiacSign\022\016.Zod" +
      "iacRequest\032\017.ZodiacResponse\"\000B\007\n\005protob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.Gate.getDescriptor(),
        }, assigner);
    proto.Gate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
